### ISSUE TITLE
About Us 

### ISSUE THREAD

**Issue by DLBPointon** [workflows-community/workflows-community.github.io#10]
About Us needs to be completed in both the main page and ./docs/AboutUs.md.

**Comment by priyanka-surana** [comment]
@workflows-community/committee I have a skeleton description for each of you but please feel to edit your details under Core team: https://workflows-community.github.io/docs/AboutUs.html

**Comment by priyanka-surana** [comment]
I am going to close this issue, but feel free to make changes to your bios 👍🏼
