### ISSUE TITLE
"Join us" slack link redirecting to Sanger login

### ISSUE THREAD

**Issue by likhitha-surapaneni** [workflows-community/workflows-community.github.io#11]
Change to a generic link accessible by both EBI and Sanger employees

**Comment by priyanka-surana** [comment]
I did not know that. I wonder how we get that link. I will email Slack Admin and check.

Can you post what the link looks like on your end? Thanks

**Comment by likhitha-surapaneni** [comment]
EBI: https://genomes-ebi.slack.com/archives/C057PFF5C3X
Sanger: https://sanger-global.slack.com/archives/C057PFF5C3X

We can have a logic for user to select org in the worst case and redirect accordingly. This only happens when user comes to the website and clicks on the url. On slack desktop app, the resolution happens automatically

**Comment by priyanka-surana** [comment]
Can you share the screenshot about what happens when you click the link? Slack team is asking for that.

**Comment by likhitha-surapaneni** [comment]
Pls find the screenshots below. The credentials do not work with email and password. When I click on the workspace `Genomes at EBI`, it doesn't take me to the exact channel

<img width="1433" alt="Screenshot 2023-06-05 at 12 29 04" src="https://github.com/workflows-community/workflows-community.github.io/assets/10923198/a6fad14d-42da-439a-ab37-143a54e3eb3c">
<img width="1433" alt="Screenshot 2023-06-05 at 12 29 15" src="https://github.com/workflows-community/workflows-community.github.io/assets/10923198/2e4ec893-9af2-47f2-afad-493da5296efa">

**Comment by priyanka-surana** [comment]
Removed the slack link instead added the channel name. Hopefully that will reduce confusion.

**Comment by priyanka-surana** [comment]
@likhitha-surapaneni Can you go back to that link (https://sanger-global.slack.com/archives/C057PFF5C3X) and this time try logging in with email and password. I am working with the Slack support team and they asked to check this. Take screenshots of what happens and then I can report back to them. Apparently the error you saw is not supposed to happen.

**Comment by priyanka-surana** [comment]
I would have thought so too, but they are convinced you should get through. I don't see how.

**Comment by likhitha-surapaneni** [comment]
In that case, let me check with someone else in EBI and see if it works. Thanks @priyanka-surana

**Comment by priyanka-surana** [comment]
Thank you for patiently for helping with this. I have updated the join us page.
