### ISSUE TITLE
Header: Simplify

### ISSUE THREAD

**Issue by priyanka-surana** [workflows-community/workflows-community.github.io#2]
I was thinking a single line across all pages. It might be cleaner. See example preview below:

<img align="left" src="https://workflows-community.github.io/logos/workflows/WCoP.png" height=50px> 

# Workflows Community of Practice

**Comment by DLBPointon** [comment]
Done
[f766c1f](https://github.com/workflows-community/workflows-community.github.io/commit/f766c1f601c9db6f3c60fce7b042d935ebab18aa)
