### ISSUE TITLE
Tabs in Header

### ISSUE THREAD

**Issue by priyanka-surana** [workflows-community/workflows-community.github.io#3]
Can we have the following tabs across all pages, it can be either on top below the header or on the left side:
- [x] About Us – a markdown page talking about what is workflows community, what we do, and who we are?
- [x] Join Us – this will have our Slack link, FRED page, mailing list, twitter, YouTube etc.
- [x] Events
- [x] Training

- [x] It would be nice if it is integrated into every page at the same location.

**Comment by DLBPointon** [comment]
This is technically done... however i need to play with the css.
960ed21

**Comment by DLBPointon** [comment]
Much easier than i expected, done.
