### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by priyanka-surana** [workflows-community/workflows-community.github.io#4]
Let's move the logos just above the footer
```
This project is maintained by [workflows-community](https://github.com/workflows-community). You can submit an issue with the site on the [GitHub Project Page](https://github.com/workflows-community/workflows-community.github.io)

Hosted on GitHub Pages — Theme by [orderedlist](https://github.com/orderedlist)
```

something like:

Supported by <img src="https://workflows-community.github.io/logos/colour/Ebi_official_logo.png" height=50px> &nbsp; <img src="https://workflows-community.github.io/logos/colour/Wellcome_Sanger_Institute_Logo_Landscape_Digital_RGB_Full_Colour.svg" height=50px> 

Put the logos in alphabetical order to avoid bias.

**Comment by DLBPointon** [comment]
Done
6c7b3d0
