### ISSUE TITLE
Event Markdown Format

### ISSUE THREAD

**Issue by priyanka-surana** [workflows-community/workflows-community.github.io#8]
Can we define the markdown format and how it gets converted in the webpage?

This is one format I use: https://raw.githubusercontent.com/sanger-tol/pipelines-website/main/markdown/events/2023/tol-hackathon-may-2023.md. This also works for the nf-core website so if we can stick to this, I can use the same file everywhere.

**Comment by DLBPointon** [comment]
Done
As of 6c7b3d0
`layout` is a required field, this decides on the html template to use for rendering.
